- name: install chrony
  apt:
    pkg:
      - chrony
- name: set pool
  lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: "^pool"
    line: pool 5.5.5.1
- name: allow nets 
  blockinfile:
    block: |
      allow 192.168.100.0/24
      allow 172.16.100.0/24
    path: /etc/chrony/chrony.conf
    state: present
- name: restart chrony
  service:
    name: chrony
    state: restarted
